server:
  servlet:
    context-path: /vpanasenkotest
  port: 8791
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:VPanasenkoTestDatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      settings:
        web-allow-others: false
      enabled: true